---
dataset: nhp
reference: hg19
contig: CH17_1-6261457
contig_files: 
    fasta: ~bnelsj/projects/kiana_chr8/ch17_sunk/CH17_1-6261457.fasta
    allelic_regions: allelic_regions.bed
species: human
ref_files: 
    hg19: 
        masked_reference: /net/eichler/vol2/eee_shared/assemblies/hg19/hg19_masked
        nhp: 
            bac_analysis: /net/eichler/vol19/projects/apes/nobackups/bknelson/peterfiles/read_depth_feb2013/bac_analysis
            split_dir: /net/eichler/vol23/projects/human_diversity/nobackups/bnelsj/CH17_nhp/index
        hgdp: 
            bac_analysis:  
            split_dir: 
    hg38: 
        masked_reference: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/hg38.rmsk_and_trf.fa
        hgdp: 
            bac_analysis: /net/eichler/vol24/projects/hg38_read_depth/nobackups/c_team/bac_analysis
            split_dir: /net/eichler/vol2/eee_shared/whole_genome_resources/hg38/hgdp/split_index}
        nhp: 
            bac_analysis: 
            split_dir: 

dataset_files: 
    hgdp: 
        bam_list: /net/eichler/vol23/projects/human_diversity/nobackups/bnelsj/hsdg/FAM115C/rd_custom_human_contig/hgdp.fully_public.224.list.tab
        sex_info: /net/eichler/vol2/eee_shared/whole_genome_resources/hgdp/sex_info
    nhp:
        bam_list: /net/eichler/vol19/projects/apes/nobackups/bnelsj/pan_pongo_bac_mapping/PAN/rd_custom_contig/pan_samples.txt
        sex_info: /net/eichler/vol19/projects/apes/nobackups/bknelson/peterfiles/read_depth_feb2013/sex_information/sex_info

gc_width: 200
mpi_mapper_path: /net/eichler/vol2/eee_shared/pipelines/MPI_mrsfast_mapping_single
